[package]
name = "tdx-measure"
description = "A library for calculating measurements of Intel TDX-protected VMs"
version.workspace = true
edition.workspace = true
license.workspace = true

[workspace]
members = ["cli"]
default-members = [".", "cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1.0"
fs-err = "3.2"
hex = "0.4"
serde_json = "1.0"

[dependencies]
anyhow.workspace = true
bon = "3.8"
fs-err.workspace = true
hex.workspace = true
hex-literal = "1.1"
log = "0.4"
object = "0.38"
serde = { version = "1.0", features = ["derive"] }
serde-human-bytes = "0.1"
serde_json.workspace = true
sha2 = "0.10"
tempfile = "3.27.0"
thiserror = "2.0"

[dev-dependencies]
serde_json.workspace = true
