[package]
name = "tdx-measure-cli"
description = "Command-line interface for calculating measurements of Intel TDX-protected VMs"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "tdx-measure"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { version = "4.5", features = ["derive"] }
fs-err.workspace = true
hex.workspace = true
serde_json.workspace = true
tdx-measure = { path = ".." }
tracing-subscriber = "0.3"
